spring:
   application:
      name: config-server
   cloud:
      config:
         server:
            git:
               uri: https://github.com/mumumushi/cloud-config-repo-demo/
               username: mumumushi
               password: RETgithub997826
             
server:
   port: 8087
   
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8081/eureka

spring.application.name=config-server